pipeline {
    agent any 
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/
                    mvn clean package
                    cd ./target/
                    ls
                '''
            }
        }

        stage ('Deploy-Tomcat') {
            steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://13.127.218.52:8080/')], 
                     contextPath: '/itdefined-war-1.0.0', 
                      war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
                }
            }
        }
    }

}
